### ISSUE TITLE
No records downloaded from HP1000 after 31/12/2023

### ISSUE THREAD

**Issue by Damien0505** [AussieSusan/HP1000#12]
Hi Susan,

Unfortunately WeeWX using your plugin has stopped download records from my HP100 since midnight New Years Eve.
The last record it will retrieve (verified by deleting last 25 records from the database and restarting WeeWX) is from 2023-12-31 23:58:28 AEDT (1704027508)

Log of restart after having deleted last 25 received records:

> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Initializing weewx version 4.10.2
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Using Python 3.9.2 (default, Feb 28 2021, 17:03:44) #012[GCC 10.2.1 20210110]
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Located at /bin/python3
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Platform Linux-5.10.0-27-amd64-x86_64-with-glibc2.31
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Locale is 'en_AU.UTF-8'
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Using configuration file /etc/weewx/weewx.conf
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: Debug is 1
> Jan  8 13:49:29 Weewx4 weewx[46802] INFO __main__: PID file is /var/run/weewx.pid
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: HP1000 Starting
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Using user-defined broadcast mask - 10.0.0.255
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Address Mask = 10.0.0.255
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Retry count = 5.000000
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Socket timeout = 5.000000
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Loop delay = 15.000000
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Retry Wait = 5.000000
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO root: HP100: Max Retry = 3.000000
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: StdConvert target unit is 0x1
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO user.weather34: service version is 0.0.5
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO user.weather34: 'None' values will be displayed as NULL
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO user.weather34: units will be displayed as METRICWX
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO user.weather34: zambretti forecast: False
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO user.weather34: Web Service: ns is running
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO user.weather34: Weather34 Weather34RealTime in cache is: True
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: Archive will use data binding wx_binding
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: Record generation will be attempted in 'hardware'
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.restx: StationRegistry: Station will be registered.
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.restx: Wunderground: Posting not enabled.
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.restx: PWSweather: Posting not enabled.
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.restx: CWOP: Posting not enabled.
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.restx: WOW: Posting not enabled.
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.restx: AWEKAS: Posting not enabled.
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: 'pyephem' detected, extended almanac data is available
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO __main__: Starting up weewx version 4.10.2
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx'
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.manager: Starting backfill of daily summaries
> Jan  8 13:49:29 Weewx4 weewx[46805] INFO weewx.manager: Daily summaries up to date
> Jan  8 13:49:35 Weewx4 weewx[46805] INFO root: HP100: Connected to address ('10.0.0.5', 62815)
> Jan  8 13:49:35 Weewx4 weewx[46805] INFO root: HP100: Established contact at 08/01/24 13:49:35
> Jan  8 13:49:35 Weewx4 weewx[46805] INFO root: HP100: Retrieving startup records
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:34:28 AEDT (1704026068) to database 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:34:28 AEDT (1704026068) to daily summary in 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:35:28 AEDT (1704026128) to database 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:35:28 AEDT (1704026128) to daily summary in 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:36:28 AEDT (1704026188) to database 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:36:28 AEDT (1704026188) to daily summary in 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:37:28 AEDT (1704026248) to database 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:37:28 AEDT (1704026248) to daily summary in 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:38:28 AEDT (1704026308) to database 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:38:28 AEDT (1704026308) to daily summary in 'weewx'
> Jan  8 13:49:55 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:39:28 AEDT (1704026368) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:39:28 AEDT (1704026368) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:40:28 AEDT (1704026428) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:40:28 AEDT (1704026428) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:41:28 AEDT (1704026488) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:41:28 AEDT (1704026488) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:42:28 AEDT (1704026548) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:42:28 AEDT (1704026548) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:43:28 AEDT (1704026608) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.restx: StationRegistry: Published record 2023-12-31 23:34:28 AEDT (1704026068)
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:43:28 AEDT (1704026608) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:44:28 AEDT (1704026668) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:44:28 AEDT (1704026668) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:45:28 AEDT (1704026728) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:45:28 AEDT (1704026728) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:46:28 AEDT (1704026788) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:46:28 AEDT (1704026788) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:47:28 AEDT (1704026848) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:47:28 AEDT (1704026848) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:48:28 AEDT (1704026908) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:48:28 AEDT (1704026908) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:49:28 AEDT (1704026968) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:49:28 AEDT (1704026968) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:50:28 AEDT (1704027028) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:50:28 AEDT (1704027028) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:51:28 AEDT (1704027088) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:51:28 AEDT (1704027088) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:52:28 AEDT (1704027148) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:52:28 AEDT (1704027148) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:53:28 AEDT (1704027208) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:53:28 AEDT (1704027208) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:54:28 AEDT (1704027268) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:54:28 AEDT (1704027268) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:55:28 AEDT (1704027328) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:55:28 AEDT (1704027328) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:56:28 AEDT (1704027388) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:56:28 AEDT (1704027388) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:57:28 AEDT (1704027448) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:57:28 AEDT (1704027448) to daily summary in 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:58:28 AEDT (1704027508) to database 'weewx'
> Jan  8 13:49:56 Weewx4 weewx[46805] INFO weewx.manager: Added record 2023-12-31 23:58:28 AEDT (1704027508) to daily summary in 'weewx'

If stopped and restarted at this point, or left to run no further records are recovered from the HP1000.

Any idea what may be causing this?

Kind regards,
Damien
(Wishing you a safe and happy 2024)

**Comment by marriotb** [comment]
This isn't a driver issue. It's a problem with the HP1000. I have found what looks like a solution, but it's a bit brutal.

If you clear the history in the device it comes right. (Go to the Factory setup page and select Clear History)

What seems to be happening is that when you first start up the driver it retrieves any historical records that it may have missed. In my case these went back to 2017.  It seems that there is a firmware limit as to how many of those the device can deal with, so when it reaches that limit it just stops. But the driver is expecting more so it hangs waiting for the next records and never gets to the next stage where it pulls in current records.

I think that the limit is in years, not records, which is why it stops at the New Year rollover.

I took the trouble to dump all the data from the device onto an SD card before clearing the history. My use case is that my historical record is in Home Assistant, so I could afford to blow away the device history. I've not looked into how to fill in the HA historical record - that's part two...

This was a weird issue to work out. My HP1000 (actually a Jaycar XC0422)  stopped uploading, but a little later than for @Damien0505. The last record in my WeeWx database is at Friday, 5 January 2024 2:35:00 PM [GMT+11:00]. That time coincided with a reboot of the server that WeeWx runs on and before I worked out what was going on it set me to searching for software that may have been upgraded and restarted at that point. The critical clue was that the failure occurred on restart and that it had previously successfully downloaded newer records than it would subsequently handle. Much studying of @AussieSusan's excellent code was necessary...

**Comment by Damien0505** [comment]
Many thanks Brian!  The limitation within the console itself was not something I had considered.  Python is far from my strongpoint, and I had come up with a dead end for everything else I had investigated.
Fortunately I was able to just delete a couple of years of data from the console and all is back up and running again..... something I will now be aware of in the future.
Thank you again for your time, and of course to Susan for the driver.

As this is a limitation of the hardware I'm happy to close the issue.

**Comment by AussieSusan** [comment]
I was not aware of this limitation either - thanks for the update.
The way the history retrieval works is that it looks at the last date in the WeeWx database and then tries to copy the history records from the console after that date.
However, as you say, it does expect to see ALL records form that date to the last in the console and (currently) there is no timeout on this.
However what I would expect (not having encountered this but other network issues that have stopped the history retrieval) is that you can kill WeeWx and restart it. It should then read the updated 'last record date' and restart the history retrieval from there.
(Also my apologies for not seeing the initial issue - for some reason I was not sent the initial posting but only the replies just now.)
Susan

**Comment by marriotb** [comment]
Killing it and restarting had no effect. It just hung at the same point, which was the last record in the previous calendar year.

My guess that the firmware only allows a three-bit field for the year number (counting from the first recorded record). My data went back to 2017, so this year becomes the eighth, causing confusion. But this only applies to the historical record access - current data is simply passed on. So the system runs until you do a restart and re-trigger the historical search.

What wasn't obvious to me was why the driver didn't just time out when the device stopped sending records. I can only presume that there is an ongoing request/response process that returns nothing but doesn't terminate the sequence.

Cheers and thanks for creating the driver in the first place - it has been (until now) a rock-solid bit of software that has run for years!

Brian
__________________________________________
Brian Marriott    ***@***.***   0419 877 684
3316 Huon Hwy, Franklin, Tasmania, 7113, Australia
VK7BM    ///catchers.shelves.dependents    QE36MV
