### ISSUE TITLE
Problem with HP100(0) Timed out too many times

### ISSUE THREAD

**Issue by jh537** [AussieSusan/HP1000#13]
Hi, unfortunately I now also have an error with HP100 after a very long time. Reinstalling the driver has failed in various ways. File brings JSON data. Thanks for the help

100661:Jan 12 07:09:44 s2 systemd[1]: Stopped LSB: weewx weather system.
100662:Jan 12 07:09:49 s2 systemd[1]: Starting LSB: weewx weather system...
100663:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Initializing weewx version 4.10.2
100664:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Using Python 3.9.2 (default, Feb 28 2021, 17:03:44) #012[GCC 10.2.1 20210110]
100665:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Located at /bin/python3
100666:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Platform Linux-5.10.0-27-amd64-x86_64-with-glibc2.31
100667:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Locale is 'de_DE.UTF-8'
100668:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Using configuration file /etc/weewx/weewx.conf
100669:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: Debug is 0
100670:Jan 12 07:09:49 s2 weewx[102793] INFO __main__: PID file is /var/run/weewx.pid
100671:Jan 12 07:09:49 s2 weewx[102796] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
100672:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: HP1000 Starting
100673:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Using user-defined broadcast mask - 192.168.17.255
100674:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Address Mask = 192.168.17.255
100675:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Retry count = 5.000000
100676:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Socket timeout = 5.000000
100677:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Loop delay = 15.000000
100678:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Retry Wait = 5.000000
100679:Jan 12 07:09:49 s2 weewx[102796] INFO root: HP100: Max Retry = 3.000000
100680:Jan 12 07:09:49 s2 weewx[102796] INFO weewx.engine: StdConvert target unit is 0x1
100681:Jan 12 07:09:49 s2 weewx[102796] INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
100682:Jan 12 07:09:49 s2 weewx[102783]: Starting weewx weather system: weewx.
100683:Jan 12 07:09:49 s2 systemd[1]: Started LSB: weewx weather system.
100684:Jan 12 07:09:49 s2 weewx[102796] INFO weewx.engine: Archive will use data binding wx_binding
100685:Jan 12 07:09:49 s2 weewx[102796] INFO weewx.engine: Record generation will be attempted in 'software'
100686:Jan 12 07:09:49 s2 weewx[102796] INFO weewx.engine: Using archive interval of 300 seconds (software record generation)
100687:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.restx: StationRegistry: Registration not requested.
100688:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.restx: Wunderground-PWS: Data for station ILIMBACH36 will be posted
100689:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.restx: PWSweather: Posting not enabled.
100690:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.restx: CWOP: Data for station CWHP1000SELO will be posted
100691:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.restx: WOW: Posting not enabled.
100692:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.restx: AWEKAS: Posting not enabled.
100693:Jan 12 07:09:50 s2 weewx[102796] INFO user.wetter: service version is 0.7
100694:Jan 12 07:09:50 s2 weewx[102796] INFO user.wetter: wetter API version is 5.0.2 - 2015/06/01
100695:Jan 12 07:09:50 s2 weewx[102796] INFO user.wetter: Data will be uploaded for station id 19820
100696:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.engine: 'pyephem' not detected, extended almanac data is not available
100697:Jan 12 07:09:50 s2 weewx[102796] INFO __main__: Starting up weewx version 4.10.2
100698:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx'
100699:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.manager: Starting backfill of daily summaries
100700:Jan 12 07:09:50 s2 weewx[102796] INFO weewx.manager: Daily summaries up to date
100704:Jan 12 07:10:15 s2 weewx[102796] INFO root: HP100: Timed out too many times
100706:Jan 12 07:10:40 s2 weewx[102796] INFO root: HP100: Timed out too many times
100710:Jan 12 07:11:05 s2 weewx[102796] INFO root: HP100: Timed out too many times
100711:Jan 12 07:11:30 s2 weewx[102796] INFO root: HP100: Timed out too many times
100713:Jan 12 07:11:55 s2 weewx[102796] INFO root: HP100: Timed out too many times
100714:Jan 12 07:12:20 s2 weewx[102796] INFO root: HP100: Timed out too many times
100718:Jan 12 07:12:45 s2 weewx[102796] INFO root: HP100: Timed out too many times
100719:Jan 12 07:12:50 s2 weewx[102796] INFO root: HP100: Connected to address ('192.168.17.57', 49170)
100720:Jan 12 07:12:51 s2 weewx[102796] INFO root: HP100: Established contact at 12/01/24 07:12:51
100721:Jan 12 07:12:51 s2 weewx[102796] INFO root: HP100: Retrieving startup records

**Comment by marriotb** [comment]
You can resolve this if you clear out all the history in the device. See my comment to #12 

Cheers
Brian

**Comment by jh537** [comment]
Hi Brian, thank you very much for writing me the solution. It is indeed due to the amount of data. I deleted the oldest year and then it worked again. I didn't realize that the station stores so much data and the SD slot works. So thanks again to you.

**Comment by marriotb** [comment]
Well done!
I'd tried deleting just one year but it refused. So I bit the bullet & deleted the lot...

Brian

**Comment by Damien0505** [comment]
Strangely enough when I first tried to delete only one year it refused.  Tried it a few times then it worked!  Strange behavior!

**Comment by jh537** [comment]
Have you tried importing data from the CSV to the database? I have tried a lot. Actually, I just wanted to load the data from 2018 from the memory card into the database. Somehow there are problems with the coding of the time format. There are no leading zeros in the CSV. Let's see, maybe I'll create another ticket.

**Comment by Damien0505** [comment]
@jh537 you mean directly importing the data into weewx using we_import?  I have done it, it really requires the date/time to be converted to epoch.  It is a bit of stuffing around but definitely possible, and works a treat once you get the CSV sorted.

Regards,
Damien

**Comment by jh537** [comment]
> @jh537 you mean directly importing the data into weewx using we_import? I have done it, it really requires the date/time to be converted to epoch. It is a bit of stuffing around but definitely possible, and works a treat once you get the CSV sorted.

Oh, that's good to know. Then I'll make it too. Thanks for the tip.

**Comment by jh537** [comment]
> @jh537 you mean directly importing the data into weewx using we_import? I have done it, it really requires the date/time to be converted to epoch. It is a bit of stuffing around but definitely possible, and works a treat once you get the CSV sorted.
> 
> Regards, Damien

Hi, unfortunately I still haven't managed to convert the date. Do you have any tips for me?
