### ISSUE TITLE
WeeWX 5.0 (compatability)

### ISSUE THREAD

**Issue by Damien0505** [AussieSusan/HP1000#14]
Not an issue, but an observation.  I have just installed WeeWX 5.0 on a VM and it appears that the HP1000 drive works with it, without issue. :)

I'll confirm this in a few days when my new install of WeeWX 4.10.2 finishes download (hopefully!) data.

(Apologies for posting this here, but there is no discussion option on this repository)

**Comment by marriotb** [comment]
Thanks for posting. 
I, too, have it running (on MacOS with Python 3.10), but I had to add another parameter to the `super(ProcessHP1000Installer, self).__init__` call in the `installer.py` code:

> `config={
>                 "HP1000": {
>                     "socket_timeout": "5",
>                     "retry_wait": "5",
>                     "retry_count": "5",
>                     "max_retry": "30",
>                     "loop_delay": "15",
>                     "driver": "user.HP1000",
>                 }
>             },
> `

**Comment by AussieSusan** [comment]
Thanks for the feedback.
I must admit that I've not touched by WeeWx system in a long time - it still ticks along doing what I intended it to.
Looks like I should check it out for other changes that could improve things.
Susan

**Comment by AussieSusan** [comment]
A new version of the driver has been released that gets around an issue in the old one when the HP1000 console reports 0 historical records for a year (in this case 2024). This caused the driver to hang.
