### ISSUE TITLE
Mistake in previous comment

### ISSUE THREAD

**Issue by marriotb** [AussieSusan/HP1000#15]
I commented previously:
I, too, have it running (on MacOS with Python 3.10), but I had to add another parameter to the `super(ProcessHP1000Installer, self).__init__` call in the `installer.py` code:

_Originally posted by @marriotb in https://github.com/AussieSusan/HP1000/issues/14#issuecomment-1890798484_

It turns out that that extra parameter was not necessary. I inserted it thinking it would solve an issue I was having, but it was not needed.

The issue I was having relates to a bug in the `weewx device` code, not the HP1000 driver. My apologies.

Brian
Edit: Oops - posted as a new issue - should have been a comment. Time to pull my head in...

**Comment by AussieSusan** [comment]
Thanks for the correction.
Also a new version of the driver has been released that gets over a problem with the HP1000 console saying that there are 0 historical records for the current year - my driver did not handle this unanticipated situation but now does.
