### ISSUE TITLE
Transfer stops

### ISSUE THREAD

**Issue by rieders** [AussieSusan/HP1000#4]
Hi there

I think the driver is great. I ran it on a Rasperry pi with weewx as a test.
I am trying to download the historical data of the weather station (HP1000). Unfortunately, it breaks off after a few seconds.
So I have to restart Weewx.
The number of dates is different.
I saw that there is a way to change a daemon file that will restart weewx if the connection breaks.
Where do I have to change that with Raspberry Pi?

Sorry for my bad english.

greetings
André

**Comment by AussieSusan** [comment]
I do all of my testing with a RPi Zero.
Getting the daemon to run is described in the HP1000 driver instructions and there are two mechanisms that can do this. I use the 'systemctl' method as I know that this lets you specify a restart interval if the daemon stops. 
The 'SysV' method is older and the RPi automatically translates the files into (what it thinks are) equivalent 'systemctl' files. I have documented my full 'systemctl' files in the WeeWx forum.
Susan

**Comment by rieders** [comment]
Hello

Unfortunately I can no longer install the HP1000 driver.
When I try to install it, I get this message.
I've tried it on different Raspberry's. Always with the same error message.
I hope you can help me because the (old) driver ran without problems so far.


pi@RaspberryZero:~ $ sudo wee_extension --install HP1000.tar.gz
Request to install 'HP1000.tar.gz'
Extracting from tar archive HP1000.tar.gz
Traceback (most recent call last):
  File "/usr/share/weewx/wee_extension", line 88, in <module>
    main()
  File "/usr/share/weewx/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 118, in install_extension
    self.tmpdir, self.logger)
  File "/usr/share/weewx/weecfg/__init__.py", line 1808, in extract_tar
    tar_archive = tarfile.open(filename, mode='r')
  File "/usr/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

Sorry for my bad english.

greetings
André

**Comment by AussieSusan** [comment]
Andre,
Can I suggest that you put this message into the weewx-user forum (making sure that you reference the HP1000 driver in the title so I see it) as the error is not coming from the driver but the installation software that I can't control.
However it would be useful if you can provide the date of the .gz file and a listing of its contents to make sure that it is the latest (for the version of WeeWx you are using) and that it contains all of the required files.
Susan
