### ISSUE TITLE
Doesn't work with the last version 4.1.1 of weewx

### ISSUE THREAD

**Issue by PoloG12** [AussieSusan/HP1000#6]
Hi,
The driver doesn't work anymore with the last (repo) installed version 4.1.1. I'm running on Fedora 5.7.15-100.fc31. The error is:

 weewxd
Traceback (most recent call last):
  File "/usr/share/weewx/weewxd", line 261, in <module>
    main()
  File "/usr/share/weewx/weewxd", line 154, in main
    engine.run()
  File "/usr/share/weewx/weewx/engine.py", line 158, in run
    self.dispatchEvent(weewx.Event(weewx.STARTUP))
  File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
    callback(event)
  File "/usr/share/weewx/weewx/engine.py", line 530, in startup
    self._catchup(self.engine.console.genStartupRecords)
  File "/usr/share/weewx/weewx/engine.py", line 638, in _catchup
    for record in generator(lastgood_ts):
  File "/usr/share/weewx/user/HP1000.py", line 795, in genStartupRecords
    self.connectToWeatherStation()
  File "/usr/share/weewx/user/HP1000.py", line 324, in connectToWeatherStation
    (self.ip_address_mask, UDP_BROADCAST_PORT))
TypeError: a bytes-like object is required, not 'str'

**Comment by siblake7** [comment]
I have the same error as above now that i've upgraded to python3, which I now get after converting the HP1000.py using 2to3 conversion tool.  is there any fix to this? Many thanks in advance.

**Comment by siblake7** [comment]
I made some changes to the HP1000.py on my local copy
line 316
 bcData = bytes("PC2000\0\0SEARCH\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 'utf-8')

line 323
(bytes(self.ip_address_mask, 'utf-8'), UDP_BROADCAST_PORT))

this appeared to fix the error I reported previously,  then I got this error

Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__: Caught unrecoverable exception:
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****  a bytes-like object is required, not 'str'
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****  Traceback (most recent call last):
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      engine.run()
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 158, in run
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      callback(event)
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 530, in startup
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      self._catchup(self.engine.console.genStartupRecords)
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 638, in _catchup
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      for record in generator(lastgood_ts):
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/user/HP1000.py", line 794, in genStartupRecords
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      self.connectToWeatherStation()
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****    File "/usr/share/weewx/user/HP1000.py", line 429, in connectToWeatherStation
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****      self.ws_socket.send(self.create_cmd_string(argument='SETUP'))
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****  TypeError: a bytes-like object is required, not 'str'
Sep  5 16:52:10 raspberrypi weewx[642] CRITICAL __main__:     ****  Exiting.

for which I update line 429 as below
 self.ws_socket.send(bytes(self.create_cmd_string(argument='SETUP'), 'utf-8'))


now I get a different error and i'm stuck

Sep  5 17:39:47 raspberrypi /weewxd: HP1000: Connected to address ('192.168.1.214', 49557)
Sep  5 17:39:47 raspberrypi /weewxd: HP1000: Established contact at 05/09/20 17:39:47
Sep  5 17:39:47 raspberrypi /weewxd: HP1000: Retrieving startup records
Sep  5 17:39:47 raspberrypi /weewxd: HP1000: Error #1
Sep  5 17:39:47 raspberrypi weewx[2144] INFO weewx.engine: Main loop exiting. Shutting engine down.
Sep  5 17:39:47 raspberrypi weewx[2144] DEBUG weewx.restx: Shut down Wunderground-PWS thread.
Sep  5 17:39:47 raspberrypi weewx[2144] DEBUG weewx.restx: Shut down StationRegistry thread.
Sep  5 17:39:47 raspberrypi weewx[2144] CRITICAL __main__: Caught WeeWxIOError:
Sep  5 17:39:47 raspberrypi weewx[2144] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...

Any help would be appreciated.

**Comment by PoloG12** [comment]
The new release works perfectly with Python 3. Thank you so much Susan! I close this ticket.
