### ISSUE TITLE
Is the WH2900 weather station a clone of the HP1000?

### ISSUE THREAD

**Issue by ProBackup-nl** [AussieSusan/HP1000#7]
The [WH2900](http://www.foshk.com/Wifi_Weather_Station/HP1000.html) is another weather station of Shenzhen Fine Offset Electronics. The device runs Easyweather firmware.

One of the differences is that a WH2900 doesn't contain an SD card slot.

Is such a WH2900 a clone of the HP1000 weather station in the sense that this software is able to retrieve data from it?

**Comment by AussieSusan** [comment]
I am not in a position to comment on this. You will need to contact the supplier/manufacturer and see if they can tell you.
Susan

**Comment by mitchellkrogza** [comment]
WH2900 is the original OEM design made my Shenzen Fine Offset Electronics, this is then manufactured by Shenzen for Ambient as their WS2902 range (clones). You can see the original design here and see it's the same device.

https://www.foshk.com/wifi_weather_station/wh2900.html

The HP1000 is completely different.

If you want a console with an SD slot then the HP2551 or HP2553 from Ecowitt is the one to go for. 

Ecowitt is the online retail brand owned by Shenzen Fine Offset Electronics themselves.
