### ISSUE TITLE
INFO root :  HP100:  timed out to many times

### ISSUE THREAD

**Issue by edegraaff** [AussieSusan/HP1000#8]
Hi, i am trying to get the driver working in my internal network to capture data from my ventus W830 (aka Ambient ws-2902a). I am trying to get it working on my pi with wired and wifi, the subnet is private network segment. De installation did not show any issues. The subnet and broadcast adres is set in the config file, seems all ok, but ... the errors are there and also not similar as you described where i would expect errors HP1000 and not HP100 

any suggestions to debug the issue? 

regards
eelco

**Comment by AussieSusan** [comment]
I cannot comment on any issues with devices that are not clones of the HP1000. I don't have access to other weather stations/consoles and s I cannot tell if they are similar enough to be made to work.
Susan
